Elearning-master/elearn/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('course.urls')),
    path('', include('app_blog.urls')),
    path('', include('video.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Elearning-master/users/urls.py
from django.conf.urls import url
from django.urls import path
from users import views
from django.contrib.auth import views as auth_views
from . import views
app_name = 'users'

urlpatterns = [

    path('student_register/', views.student_register, name='student_register'),
    path('instructor_register/', views.instructor_register,
         name='instructor_register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='users_login'),
    # path('login/', views.login_page, name='login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('user_login/', views.user_login, name='user_login'),
    path('register/', views.user_register, name='user_register'),
    path('profile/', views.profile, name='user_profile'),
    # path('teachers/', views.teacher, name='teachers'),
    # path('teachers-single/<int:lecturerId>',
    #      views.teacher_single, name='teachers-single'),
]

Elearning-master/video/urls.py
from django.urls import path
from video import views

app_name = 'video'

urlpatterns = [
    path('videolist/<int:user_id>/', views.videolist, name='videolist'),
    path('course_videolist/<int:course_id>/', views.course_videolist, name='course_videolist'),
    path('video_delete/<int:x_id>/', views.video_delete, name='video_delete'),
]

Elearning-master/video/models.py
from django.db import models
from .validators import file_size
from course.models import Course

# Create your models here.


class Video(models.Model):
    Course = models.ForeignKey('course.Course', db_column='Course',on_delete=models.CASCADE, default= -10)
    caption = models.CharField(max_length=100)
    video = models.FileField(upload_to="video/%y", validators=[file_size])
    

    def __str__(self):
        return self.caption

Elearning-master/video/forms.py
from .models import Video
from django import forms
from course.models import Course


class Video_form(forms.ModelForm):
    def __init__(self, user_id, *args, **kwargs):
        super(Video_form, self).__init__(*args, **kwargs)  # populates the post
        self.fields['Course'].queryset = Course.objects.filter(instructor= user_id)
        
    class Meta:
        model = Video
        fields = "__all__"

Elearning-master/video/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from .forms import Video_form
from .models import Video
from course.models import Course
from users.models import Student, Instructor as ins, User
from django.contrib import messages


def videolist(request,user_id):
    form = Video_form(user_id)
    if request.method == "POST":

        form = Video_form(user_id,data=request.POST, files=request.FILES)
        form.fields["Course"].queryset = Course.objects.filter(instructor = user_id)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your Requested Video is uploaded.')
            return HttpResponseRedirect(reverse('course:course_home'))
        else:
            form = Video_form(user_id)
    return render(request, 'video_form.html', {"form": form})



def course_videolist(request,course_id):
    cour = Course.objects.get(pk=course_id)
    all_video = Video.objects.filter(Course=course_id)
    instr = User.objects.get(pk=request.user.id)
    diction = {'course': cour, 'instructor': instr, "all": all_video}

    return render(request, 'course_videolist.html', context=diction)


def video_delete(request, x_id):
    Video.objects.filter(pk = x_id).delete()
    messages.success(request, 'Selected Video is removed')
    return HttpResponseRedirect(reverse('course:course_home'))

Elearning-master/video/templates/course_videolist.html
{% extends "base.html" %}
{% block content %}




<div class="container">
    <h3>List of Videos</h3>
<table class="table table-bordered">
    <tr>
        <th>Video Caption</th>
        <th>Video</th>
        <th>Delete</th>

    </tr>
    {% for x in all %}
    <tr>
        <td>{{x.caption}}</td>
        <td><video class="embed-responsive embed-responsive-16by9" controls="controls"><source src="{{x.video.url}}" type="video/mp4" /></video></td>
        <td>
        <form action="{% url 'video:video_delete' x.id %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="subject" value="{{ x.id }}" />
            <div class="price-button pt-10">

                <button type="submit" class="btn btn-danger btn-md">Remove</a>
            </div>
        </form>
        </td>

    </tr>
    {% endfor %}
</table>
</div>





{% endblock content %}

Elearning-master/video/templates/video_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block styles %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
{% endblock %}

{% block content %}


    <div class="container">
      <div class="course-video">


        <h1 style:"font-weight:bold;">Add Tutorials in Your Courses</h1>
        <div class="mt-5">
            <form action="." method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{form | crispy}}
                <button class="btn btn-success btn-md">Upload</button>

            </form>
        </div>

        <hr>
          </div>


    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>
{% endblock %}