Elearning-master/app_blog/urls.py
from django.conf.urls import url
from django.urls import path
from app_blog import views

app_name = 'app_blog'

urlpatterns = [

    path('write/',views.CreateBlog.as_view(),name='create_blog'),
    path('blog_list/',views.BlogList.as_view(), name= 'blog_list'),
    path('details/<slug:slug>',views.blog_details,name='blog_details'),
    path('my_blogs/', views.MyBlogs.as_view(), name='my_blogs'),
    path('edit_blog/<pk>/', views.UpdateBlog.as_view(), name='edit_blog'),
    path('delelte_blog/<pk>/', views.DeleteBlog.as_view(), name='delete_blog'),




]

Elearning-master/course/urls.py
from django.conf.urls import url
from django.urls import path
from course import views

app_name = 'course'

urlpatterns = [

    path('', views.home, name='course_home'),
    path('about/', views.about, name='course-about'),
    path('donate/', views.donate, name='donate'),
    path('instructor_course/<int:user_id>/', views.instructor_course,name='instructor_course'),
    path('my_courses/<int:user_id>/',views.my_courses, name='my_courses'),
    path('student_my_courses/<int:user_id>/', views.student_my_courses, name='student_my_courses'),
    path('course_list/', views.course_list, name='course_list'),
    path('courses_single/<int:course_id>/', views.courses_single, name='courses_single'),
    path('course_enroll/<int:course_id>/',views.course_enroll, name='course_enroll'),
    path('course_dismiss/<int:course_id>/',views.course_dismiss, name='course_dismiss'),

]

Elearning-master/elearn/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('course.urls')),
    path('', include('app_blog.urls')),
    path('', include('video.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Elearning-master/users/urls.py
from django.conf.urls import url
from django.urls import path
from users import views
from django.contrib.auth import views as auth_views
from . import views
app_name = 'users'

urlpatterns = [

    path('student_register/', views.student_register, name='student_register'),
    path('instructor_register/', views.instructor_register,
         name='instructor_register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='users_login'),
    # path('login/', views.login_page, name='login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('user_login/', views.user_login, name='user_login'),
    path('register/', views.user_register, name='user_register'),
    path('profile/', views.profile, name='user_profile'),
    # path('teachers/', views.teacher, name='teachers'),
    # path('teachers-single/<int:lecturerId>',
    #      views.teacher_single, name='teachers-single'),
]

Elearning-master/video/urls.py
from django.urls import path
from video import views

app_name = 'video'

urlpatterns = [
    path('videolist/<int:user_id>/', views.videolist, name='videolist'),
    path('course_videolist/<int:course_id>/', views.course_videolist, name='course_videolist'),
    path('video_delete/<int:x_id>/', views.video_delete, name='video_delete'),
]

Elearning-master/course/models.py
from django.db import models
from users.models import Student, Instructor,User



# Create your models here.

class Course(models.Model):
    name = models.CharField(max_length=100)
    course_description = models.TextField(blank=True, null=True)
    instructor = models.ForeignKey('users.User', db_column='instructor',  on_delete=models.CASCADE)

    class Meta:
        db_table = 'course'

    def __str__(self):
        return self.name

class Enrollment(models.Model):
    encourse = models.ForeignKey('course.Course', db_column='Course',  on_delete=models.CASCADE, )
    student = models.ForeignKey('users.User', db_column='Student',  on_delete=models.CASCADE, )
    status = models.IntegerField(blank=True,null=True)
    
    class Meta:
        managed = True
        db_table = "enrollment"

Elearning-master/course/forms.py
from django import forms

from users.models import Student, Instructor
from course.models import Course, Enrollment
from django.contrib.auth import get_user_model

User = get_user_model()

class CourseForm(forms.ModelForm):
    

    class Meta():
        model = Course
        fields = ('name', 'course_description')

Elearning-master/course/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.http import HttpResponse
from django.core.paginator import Paginator
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page
from django.views.decorators.vary import vary_on_cookie
from django.views.generic import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin

from django.shortcuts import render
from course import forms
import course
from course.forms import CourseForm
from users.models import Student, Instructor as ins, User
from course.models import Course as cs, Enrollment
from video.models import Video
from django.contrib.auth import get_user_model

User = get_user_model()

# Create your views here.


# def index(request):
#     dict = {}
#     if request.user.is_authenticated:
#         current_user = request.user
#         user_id = current_user.id
#         user_basic_info = User.objects.get(pk=user_id)
#         try:
#             student_more_info = Student.objects.get(user__pk=user_id)
#         except:
#             instructor_more_info = Instructor.objects.get(user_id=user_id)
#         try:
#             if instructor_more_info.is_instructor:
#                 dict = {'user_basic_info': user_basic_info,
#                         'user_more_info': instructor_more_info}
#         except:
#             dict = {'user_basic_info': user_basic_info,
#                     'user_more_info': student_more_info}

#     return render(request, 'index.html', context=dict)

def home(request):
    context = {'home_page': 'active'}
    return render(request, 'index.html', context)


def about(request):
    context = {'about_page': 'active'}
    return render(request, 'about.html', context)


def donate(request):
    context = {'donate': 'active'}
    return render(request, 'donate.html', context)

    
# def instructor_course(request):
#     if request.user.is_authenticated:
#         current_user = request.user
#         user_id = current_user.id
#         user_basic_info = User.objects.get(pk=user_id)
#         user_more_info = Instructor.objects.get(user__pk=user_id)
    
#     if add.method == 'POST':
#         course_form = CourseForm(data=request.POST)

#         if course_form.is_valid:
#             course_form.save(commit=True)
#             return index(request)

#     dict = {'course_form': course_form, 'user_basic_info': user_basic_info, 'user_more_info': user_more_info}

#     return render(request, 'instructor_course.html', context=dict)


def instructor_course(request, user_id):
    user = User.objects.get(pk=user_id)
    course_form = forms.CourseForm()
    if request.method == 'POST':
        course_form = CourseForm(data=request.POST)

        if course_form.is_valid():
            course = course_form.save(commit=False)
            course.instructor = request.user
            course.save()
            return HttpResponseRedirect(reverse('course:course_home'))
    else:
             
        dict = {'course_form': course_form}
        return render(request, 'instructor_course.html', context=dict)


def my_courses(request, user_id):
    course_list = cs.objects.filter(instructor = user_id)

    ins_details = User.objects.get(pk = user_id)
    
    diction = {'title': 'List of Courses', 'course_list': course_list,'ins_details': ins_details}
    return render(request, 'my_courses.html', context=diction)


def course_list(request):
    course_list = cs.objects.all()
    diction = {'title': 'List of Courses','course_list': course_list}
    return render(request, 'course_list.html', context=diction)


def student_my_courses(request, user_id):
    selected = Enrollment.objects.filter(student = user_id)
    course_pk =[]
    for x in selected:
        y = x.encourse
        course_pk.append(y.id)

    course_list = cs.objects.filter(pk__in = course_pk)
    print(course_list)
    print(user_id)
    diction = {'title': 'List of Courses', 'course_list': course_list}
    return render(request, 'student_my_courses.html', context=diction)


def courses_single(request, course_id):
    if request.user.is_authenticated:
        field = 'instructor'
        cour = cs.objects.get(pk = course_id)
        
        field_value = getattr(cour, field)
        us = cour.instructor
        instr = User.objects.get(pk = us.id)

        enrollment = Enrollment.objects.filter(encourse = course_id , student = request.user.id).first()
        all_video = Video.objects.filter(Course = course_id)
        diction = {'course': cour, 'instructor': instr,'enrollment': enrollment, "all": all_video}
        return render(request, 'courses_single.html', context=diction)
    else:
        messages.success(request, 'You are not Registered !! Register NOW!')
        return HttpResponseRedirect(reverse('users:user_register'))


@login_required
def course_enroll(request,course_id):
    
    if request.method == 'POST':
        
        
        current_student = User.objects.get(pk = request.user.id)
        cour = cs.objects.get(pk=course_id)
        
        if( cour != 0):
        
            Enrollment.objects.create(encourse= cour, student = current_student, status= 1)
        
            
            messages.success(request, 'You have enrolled the Course.')
        else:
            messages.error(request)

    return HttpResponseRedirect(reverse('course:course_home'))


def course_dismiss(request, course_id):
    if request.method == 'POST':
        current_student = User.objects.get(pk=request.user.id)
        cour = cs.objects.get(pk=course_id)

        Enrollment.objects.filter(encourse=course_id, student=request.user.id, status = 1).delete()
        
        messages.success(request, 'You have Unenrolled the Course.')
        return HttpResponseRedirect(reverse('course:course_home'))
    else:
        messages.error(request)

Elearning-master/course/templates/blog_details.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {{blog.blog_title}} {% endblock %}
{% block content %}
<div class="container">
  <div class="row">

    <div class="col-sm-12">
      <h2>{{blog.blog_title}}</h2>
      <h4>Posted By: {{blog.instructor}}</h4>
      <i>
        <h6>Published On: {{blog.publish_date}}</h6>
      </i>
      <br>
      <i>
        <h6>Updated On: {{blog.update_date}}</h6>
      </i>
    </div>


    <p style="padding-left:50px;">
      {{blog.blog_content|linebreaks}}
    </p>
    <hr>





    <br>
    <br>
  </div>
</div>

{% endblock content %}

Elearning-master/course/templates/blog_list.html
{% extends 'base.html' %}
{% load custom_filters %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
{% for blog in blogs%}

<h3>{{blog.blog_title}}</h3>
<h5><i>{{blog.publish_date}}</i></h5>

<div class="row">

  <div class="col-sm-12">
    <p>{{blog.blog_content|range_filter|linebreaks}}
      {% if user.is_authenticated %}
      <a href="{% url 'app_blog:blog_details' slug=blog.slug %}">Read More</a>
      {% else %}
        <a href="{% url 'users:user_login' %}">Read More</a>
      {% endif %}

    </p>
   <h5>Posted By: <a href="#">{{blog.instructor|linebreaks}}</a></h5>
  </div>
    </div>

    <hr>


{% endfor %}
  </div>
{% endblock content %}

Elearning-master/course/templates/course_list.html
{% extends "base.html" %}
{% load static %}
{% load random_numbers %}
{% block content %}
    <!--====== PAGE BANNER PART START ======-->

    <section id="page-banner" class="pt-105 pb-110 bg_cover" data-overlay="8" style="background-image: url('/static/images/page-banner-1.jpg')">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="page-banner-cont">
                        <h2>Our Courses</h2>
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{% url 'course:course_home' %}">Home</a></li>
                                <li class="breadcrumb-item active" aria-current="page">Courses</li>
                            </ol>
                        </nav>
                    </div>  <!-- page banner cont -->
                </div>
            </div> <!-- row -->
        </div> <!-- container -->
    </section>

    <!--====== PAGE BANNER PART ENDS ======-->

    <!--====== COURSES PART START ======-->

    <section id="courses-part" class="pt-60 pb-60 gray-bg">
        <div class="container">
            <div class="row">
                {% for course in course_list %}
                    <div class="col-lg-4 col-md-6">
                        <div class="single-course mt-30">
                            <div class="thum">

                              <div class="image">
                                  <img src="/static/images/course/cu-{{ forloop.counter }}.jpg" alt="Course">
                              </div>
                                <div class="price">

                                </div>
                            </div>
                            <div class="cont">


                                <a href="{% url 'course:courses_single' course.id  %}"><h4>{{ course.name }}</h4></a>
                                <div class="course-teacher">
                                    
                                    <div class="name">
                                        <a href="#"><h6>{{course.instructor}}</h6></a>
                                    </div>
                                    <div class="admin">

                                    </div>
                                </div>
                            </div>
                        </div> <!-- single course -->
                    </div>
                {% endfor %}
            </div> <!-- row -->
            
        </div> <!-- container -->
    </section>

    <!--====== COURSES PART ENDS ======-->

{% endblock content %}

Elearning-master/course/templates/courses_single.html
{% extends "base.html" %}
{% load static %}
{% load random_numbers %}
{% block content %}

    <!--====== PAGE BANNER PART START ======-->

    <!--====== PAGE BANNER PART ENDS ======-->

    <!--====== COURSES SINGEl PART START ======-->

    <section id="courses-single" class="pt-90 pb-120 gray-bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="courses-single-left mt-30">
                        <div class="title">
                            <h3>{{course.name}}</h3>
                        </div> <!-- title -->

                        <div class="course-terms">

                                    <div class="teacher-name">

                                        <div class="name">

                                            <h6>{{instructor.username}}</h6>
                                        </div>
                                    </div>

                        </div> <!-- course terms -->


                        <div class="courses-single-image pt-50">
                            <img src="{% static 'images/course/cu-1.jpg' %}" alt="Courses">
                        </div> <!-- courses single image -->
                        <div class="row">
                            <div class="col-lg-12 col-md-6">
                                <div class="course-features mt-30">


                                    {% if  enrollment.encourse == course and enrollment.student == user %}
                                    <form action="{% url 'course:course_dismiss' course.id %}" method="POST">
                                        {% csrf_token %}
                                        <input type="hidden" name="subject" value="{{ course.id }}" />
                                        <div class="price-button pt-10">
                                            <span>Enrolled</span>
                                            <button type="submit" class="main-btn">Dismiss Now</a>
                                        </div>
                                    </form>
                                    {% else %}
                                    <form action="{% url 'course:course_enroll' course.id %}" method="POST">
                                        {% csrf_token %}
                                        <input type="hidden" name="subject" value="{{ course.id }}" />
                                        <div class="price-button pt-10">

                                            <button type="submit" class="main-btn" style="margin-left:50px;">Enroll Now</a>
                                        </div>
                                    </form>
                                    {% endif %}
                                </div>

                            </div>

                        </div>

                        <div class="courses-tab mt-30">
                            <ul class="nav nav-justified" id="myTab" role="tablist">
                                <li class="nav-item">
                                    <a class="active" id="overview-tab" data-toggle="tab" href="#overview" role="tab" aria-controls="overview" aria-selected="true">Overview</a>
                                </li>
                                <li class="nav-item">
                                    <a id="curriculum-tab" data-toggle="tab" href="#curriculum" role="tab" aria-controls="curriculum" aria-selected="false">Videos</a>
                                </li>
                                <li class="nav-item">
                                    <a id="instructor-tab" data-toggle="tab" href="#instructor" role="tab" aria-controls="instructor" aria-selected="false">Instructor</a>
                                </li>

                            </ul>

                            <div class="tab-content" id="myTabContent">
                                <div class="tab-pane fade show active" id="overview" role="tabpanel" aria-labelledby="overview-tab">
                                    <div class="overview-description">
                                        <div class="single-description pt-40">
                                            <h6>Course Summery</h6>
                                            <p>{{course.course_description}}</p>
                                        </div>

                                    </div> <!-- overview description -->
                                </div>

                                <div class="tab-pane fade" id="curriculum" role="tabpanel" aria-labelledby="curriculum-tab">
                                    <div class="curriculum-cont">

                                        <div class="accordion" id="accordionExample">
                                            {% if enrollment.encourse == course and enrollment.student == user %}
                                            {% for x in all %}
                                            <h3 class="text-center mt-2 mb-2">{{x.caption}}</h3>
                                            <video class="embed-responsive embed-responsive-16by9" controls="controls">
                                                <source src="{{x.video.url}}" type="video/mp4" />
                                            </video>
                                            {% endfor %}
                                            {% endif %}
                                        </div>
                                    </div> <!-- curriculum cont -->
                                </div>
                                <div class="tab-pane fade" id="instructor" role="tabpanel" aria-labelledby="instructor-tab">
                                    <div class="instructor-cont">
                                        <div class="instructor-author">
                                            <div class="author-thum">
                                                <img src="{% static 'images/instructor/i-1.jpg' %}" alt="Instructor">
                                            </div>
                                            <div class="author-name">
                                                <a href="#"><h5>{{instructor.username}}</h5></a>

                                                <ul class="social">
                                                    <li><a href="#"><i class="fa fa-facebook-f"></i></a></li>
                                                    <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                                    <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                                                </ul>
                                            </div>
                                        </div>
                                        <div class="instructor-description pt-25">
                                          <h4>Contact</h4>
                                            <p>Email: {{instructor.email}}</p>
                                        </div>
                                    </div> <!-- instructor cont -->
                                </div>







                        </div> <!-- row -->
                    </div> <!-- related courses -->
                </div>
            </div> <!-- row -->
        </div> <!-- container -->
    </section>





{% endblock content %}

Elearning-master/course/templates/create_blog.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
<h2>Write Your Blog Here: </h2>
<form method="POST" enctype="multipart/form-data">
  {{form|crispy}}
  {% csrf_token%}
  <button type="submit" class="btn btn-success btn-md" style="margin-bottom:30px;margin-top:30px;">Publish</button>

</form>
</div>
{% endblock content %}

Elearning-master/course/templates/delete_blog.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {{blog.blog_title}} {% endblock %}
{% block content %}
<div class="container">
{% if blog.instructor == user %}
<form method="POST">
{{form|crispy}}
{% csrf_token %}
<strong>Are You Sure?</strong><br>
<button type="submit" name="button" class="btn btn-success" style="margin-bottom:30px;margin-top:30px;">Yes</button>


{% else %}
<p>Your are not allowed to view this page. 404</p>
</form>
{% endif %}
</div>
{% endblock content %}

Elearning-master/course/templates/donate.html
{% extends "base.html" %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/donate.css' %}">
{% endblock %}
{% block content %}
<div class="row">


    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 text-center"  >

    <div class="donate"> </div>
    </div>
    </div>
    <div class="container text-center">
      <div class="donatepara">
        <p>We make many contributions for several challenges. Now the world is facing an unprecedented challenge with
          communities
          and economies everywhere affected by the growing COVID-19 pandemic.We can now help people and supporting them by
          donating any amount.</b> </p>
      </div>
    </div>
    

     <div class="donatemain">

       <div class="card text-center">
 <div class="card-header" style="font-weight: 900">
   Donate For Covid-19 Patients
 </div>
 <div class="card-body">
    <a href="#" class="btn btn-primary">Donate Any Amount</a>

   <p class="card-text"style="margin-top:10px;">Thanks in Advance.</p>

 </div>
 <div class="card-footer text-muted">
   "No one has ever become poor by giving"
 </div>
</div>



     </div>


     {% endblock %}

Elearning-master/course/templates/edit_blog.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {{blog.blog_title}} {% endblock %}
{% block content %}
<div class="container">
    {% if blog.instructor == user %}
    <form method="POST">
        {{form|crispy}}
        {% csrf_token %}
        <button type="submit" name="button" class="btn btn-success"
            style="margin-bottom:30px;margin-top:30px;">Update</button>
        {% else %}
        <p>Your are not allowed to view this page. 404</p>
    </form>
    {% endif %}
</div>
{% endblock content %}

Elearning-master/course/templates/instructor_course.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class=container>
  <div class="create-video">
    <h2>Create Course</h2>


<form method="POST">
{% csrf_token %}
{{course_form | crispy}}
<div class="button-box">

    <button class="btn btn-success btn-md" type="submit" style="margin-bottom:30px;margin-top:20px;"><span>Create Course</span></button>
</div>
</form>
</div>
  </div>

{% endblock content %}

Elearning-master/course/templates/my_blogs.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block title_block %} {{user}} {% endblock %}
{% block content %}
<div class="container">
  {% for blog in user.post_author.all %}
  <h3>{{blog.blog_title}}</h3>
  <h6>{{blog.publish_date}}</h6>
  <div class="row">

    <div class="col-sm-8">
      <p>{{blog.blog_content|range_filter|linebreaks}}</p>
      <a href="{% url 'app_blog:blog_details' slug=blog.slug %}">Read More</a>
    </div>
  </div>
  <!-- <button type="button" class="btn btn-dark">Dark</button> -->
  <a href="{% url 'app_blog:edit_blog' pk=blog.pk %}" class="btn btn-dark"
    style="margin-bottom:25px;margin-top:20px;">Edit</a>
  <a href="{% url 'app_blog:delete_blog' pk=blog.pk %}" class="btn btn-dark"
    style="margin-bottom:25px;margin-top:20px;">Delete</a>

  <hr>

  {% endfor %}
</div>
{% endblock content %}

Elearning-master/course/templates/my_courses.html
{% extends "base.html" %}
{% load static %}
{% load random_numbers %}
{% block content %}
<!--====== PAGE BANNER PART START ======-->

<section id="page-banner" class="pt-105 pb-110 bg_cover" data-overlay="8"
    style="background-image: url('/static/images/page-banner-1.jpg')">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="page-banner-cont">
                    <h2>My Courses</h2>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{% url 'course:course_home' %}">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Courses</li>
                        </ol>
                    </nav>
                </div> <!-- page banner cont -->
            </div>
        </div> <!-- row -->
    </div> <!-- container -->
</section>

<!--====== PAGE BANNER PART ENDS ======-->

<!--====== COURSES PART START ======-->

<section id="courses-part" class="pt-60 pb-60 gray-bg">
    <div class="container">
        <div class="row">
            {% for course in course_list %}
            <div class="col-lg-4 col-md-6">
                <div class="single-course mt-30">
                    <div class="thum">

                        <div class="image">
                            <img src="/static/images/course/cu-{{ forloop.counter }}.jpg" alt="Course">
                        </div>
                        <div class="price">

                        </div>
                    </div>
                    <div class="cont">


                        <a href="{% url 'video:course_videolist' course.id  %}">
                            <h4>{{ course.name }}</h4>
                        </a>
                        <div class="course-teacher">

                            <div class="name">
                                <a href="#">
                                    <h6>{{course.instructor}}</h6>
                                </a>
                            </div>
                            <div class="admin">

                            </div>
                        </div>
                    </div>
                </div> <!-- single course -->
            </div>
            {% endfor %}
        </div> <!-- row -->

    </div> <!-- container -->
</section>

<!--====== COURSES PART ENDS ======-->

{% endblock content %}

Elearning-master/course/templates/student_my_courses.html
{% extends "base.html" %}
{% load static %}
{% load random_numbers %}
{% block content %}
<!--====== PAGE BANNER PART START ======-->

<section id="page-banner" class="pt-105 pb-110 bg_cover" data-overlay="8"
    style="background-image: url('/static/images/page-banner-1.jpg')">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="page-banner-cont">
                    <h2>My Courses</h2>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{% url 'course:course_home' %}">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Courses</li>
                        </ol>
                    </nav>
                </div> <!-- page banner cont -->
            </div>
        </div> <!-- row -->
    </div> <!-- container -->
</section>

<!--====== PAGE BANNER PART ENDS ======-->

<!--====== COURSES PART START ======-->

<section id="courses-part" class="pt-60 pb-60 gray-bg">
    <div class="container">
        <div class="row">
            {% for course in course_list %}
            <div class="col-lg-4 col-md-6">
                <div class="single-course mt-30">
                    <div class="thum">

                        <div class="image">
                            <img src="/static/images/course/cu-{{ forloop.counter }}.jpg" alt="Course">
                        </div>
                        <div class="price">

                        </div>
                    </div>
                    <div class="cont">


                        <a href="{% url 'course:courses_single' course.id  %}">
                            <h4>{{ course.name }}</h4>
                        </a>
                        <div class="course-teacher">

                            <div class="name">
                                <a href="#">
                                    <h6>{{course.instructor}}</h6>
                                </a>
                            </div>
                            <div class="admin">

                            </div>
                        </div>
                    </div>
                </div> <!-- single course -->
            </div>
            {% endfor %}
        </div> <!-- row -->

    </div> <!-- container -->
</section>

<!--====== COURSES PART ENDS ======-->

{% endblock content %}