Elearning-master/course/urls.py
from django.conf.urls import url
from django.urls import path
from course import views

app_name = 'course'

urlpatterns = [

    path('', views.home, name='course_home'),
    path('about/', views.about, name='course-about'),
    path('donate/', views.donate, name='donate'),
    path('instructor_course/<int:user_id>/', views.instructor_course,name='instructor_course'),
    path('my_courses/<int:user_id>/',views.my_courses, name='my_courses'),
    path('student_my_courses/<int:user_id>/', views.student_my_courses, name='student_my_courses'),
    path('course_list/', views.course_list, name='course_list'),
    path('courses_single/<int:course_id>/', views.courses_single, name='courses_single'),
    path('course_enroll/<int:course_id>/',views.course_enroll, name='course_enroll'),
    path('course_dismiss/<int:course_id>/',views.course_dismiss, name='course_dismiss'),

]

Elearning-master/elearn/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('course.urls')),
    path('', include('app_blog.urls')),
    path('', include('video.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Elearning-master/users/urls.py
from django.conf.urls import url
from django.urls import path
from users import views
from django.contrib.auth import views as auth_views
from . import views
app_name = 'users'

urlpatterns = [

    path('student_register/', views.student_register, name='student_register'),
    path('instructor_register/', views.instructor_register,
         name='instructor_register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='users_login'),
    # path('login/', views.login_page, name='login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('user_login/', views.user_login, name='user_login'),
    path('register/', views.user_register, name='user_register'),
    path('profile/', views.profile, name='user_profile'),
    # path('teachers/', views.teacher, name='teachers'),
    # path('teachers-single/<int:lecturerId>',
    #      views.teacher_single, name='teachers-single'),
]

Elearning-master/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    is_student = models.BooleanField(default=False)
    is_instructor = models.BooleanField(default=False)




class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    Dob = models.DateField()
    GENDER_MALE = 0
    GENDER_FEMALE = 1
    GENDER_OTHERS = -1
    GENDER_CHOICES = [(GENDER_MALE, 'Male'), (GENDER_FEMALE,'Female'), (GENDER_OTHERS, 'Others')]
    gender = models.IntegerField(choices=GENDER_CHOICES, default=None)
    

    


class Instructor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    Dob = models.DateField()
    GENDER_MALE = 0
    GENDER_FEMALE = 1
    GENDER_OTHERS = -1
    GENDER_CHOICES = [(GENDER_MALE, 'Male'), (GENDER_FEMALE,
                                              'Female'), (GENDER_OTHERS, 'Others')]
    gender = models.IntegerField(choices=GENDER_CHOICES, default=None)
    

    

Elearning-master/users/forms.py
from django import forms
from django.contrib.auth.models import User
from users.models import Student, Instructor
from django.contrib.auth import get_user_model

User = get_user_model()


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    email = forms.EmailField(required=True)

    class Meta():
        model = User
        fields = ('username', 'email', 'password')


class StudentInfoForm(forms.ModelForm):
    Dob = forms.DateField(widget=forms.TextInput(attrs={'type': 'date'}),label="Date of Birth")

    class Meta():
        model = Student
        fields = ('Dob', 'gender')



class InstructorInfoForm(forms.ModelForm):
    Dob = forms.DateField(widget=forms.TextInput(attrs={'type': 'date'}),label="Date of Birth")

    class Meta():
        model = Instructor
        fields = ('Dob', 'gender')

Elearning-master/users/views.py
from django.contrib import messages
from django.shortcuts import render
from users.forms import UserForm, StudentInfoForm, InstructorInfoForm
from users.models import Student, Instructor
from django.contrib.auth.models import User

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.urls import reverse
# Create your views here.


def student_register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        student_info_form = StudentInfoForm(data=request.POST)

        if user_form.is_valid() and student_info_form.is_valid():
            user = user_form.save(commit=False)
            user.is_student = True
            user.is_instructor = False
            user.set_password(user.password)
            user.save()

            student_info = student_info_form.save(commit=False)
            student_info.user = user
            student_info.save()
            registered = True
    else:
        user_form = UserForm()
        student_info_form = StudentInfoForm()
    dict = {'user_form': user_form,
            'student_info_form': student_info_form, 'registered': registered}
    if registered == True:
        messages.success(request, 'Successfully Registered !')
    return render(request, 'student_register.html', context=dict)


def instructor_register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)

        instructor_info_form = InstructorInfoForm(data=request.POST)

        if user_form.is_valid() and instructor_info_form.is_valid():
            user = user_form.save(commit=False)
            user.is_instructor = True
            user.is_student = False
            user.set_password(user.password)
            user.save()

            instructor_info = instructor_info_form.save(commit=False)
            instructor_info.user = user
            instructor_info.save()
            registered = True
    else:
        user_form = UserForm()
        instructor_info_form = InstructorInfoForm()
    if registered == True:
        messages.success(request, 'Successfully Registered !')
    dict = {'user_form': user_form,
            'instructor_info_form': instructor_info_form, 'registered': registered}

    return render(request, 'instructor_register.html', context=dict)


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse("course:course_home"))

            else:
                return HttpResponse("Account is not active!!")
        else:
            messages.success(request, 'Login Informations are wrong. Try Again!!')
            return HttpResponseRedirect(reverse('users:user_login'))
            
    else:
        return render(request, 'login.html', context={})


def login_page(request):
    return render(request, 'login.html', context={})


def user_register(request):
    context = {'home_page': 'active'}
    return render(request, 'user_register.html', context)


@login_required
def profile(request):
    context = {'home_page': 'active'}
    return render(request, 'profile.html', context)


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('course:course_home'))

Elearning-master/users/templates/instructor_register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<!--====== PAGE BANNER PART START ======-->

<section id="page-banner" class="pt-105 pb-110 bg_cover" data-overlay="8"
    style="background-image: url('/static/images/page-banner-1.jpg')">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="page-banner-cont">
                    <h2>Register</h2>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{% url 'course:course_home' %}">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page"> Instructor Register</li>
                        </ol>
                    </nav>
                </div> <!-- page banner cont -->
            </div>
        </div> <!-- row -->
    </div> <!-- container -->
</section>

<!--====== PAGE BANNER PART ENDS ======-->
<div class="login-register-area pt-60 pb-60">
    <div class="container">
        <div class="row">
            <div class="col-lg-7 col-md-12 ml-auto mr-auto">
                <div class="login-register-wrapper">
                    <div class="tab-content">
                        <div class="login-form-container">
                            <div class="login-register-form">
                                <form method="post">
                                    {% csrf_token %}
                                    {{user_form | crispy}}
                                    {{instructor_info_form | crispy}}
                                    <!-- <input type="text" name="user-name" placeholder="Username">
                                    <input type="password" name="user-password" placeholder="Password">
                                    <input name="user-email" placeholder="Email" type="email"> -->
                                    <div class="button-box">
                                        <button class="btn btn-success btn-md" type="submit"style="margin-bottom:10px;margin-top:30px;"><span>Register</span></button>
                                    </div>
                                    <div class="pt-3">
                                        <small class="text-muted">
                                            Already Have An Account? <a class="ml-2"
                                                href="{% url 'users:user_login' %}">Sign
                                                In</a>
                                        </small>
                                    </div>
                                </form>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- {% if registered %}

<div class="alert alert-success">Congratulations! Registration Successful !!</div>
{% else %}
<form enctype='multipart/form-data' method="POST">
    {{user_form | crispy}}
    {{instructor_info_form | crispy}}
    {% csrf_token %}

    <input type="submit" name="submit" value="Register">
</form>

{% endif %} -->

{% endblock content %}

Elearning-master/users/templates/login.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block styles %}
<link rel="stylesheet" href="{% static 'users/css/users_style.css' %}">
{% endblock %}
{% block content %}
<!--====== PAGE BANNER PART START ======-->

<section id="page-banner" class="pt-105 pb-110 bg_cover" data-overlay="8"
    style="background-image: url('/static/images/page-banner-1.jpg')">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="page-banner-cont">
                    <h2>Login</h2>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{% url 'course:course_home' %}">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Login</li>
                        </ol>
                    </nav>
                </div> <!-- page banner cont -->
            </div>
        </div> <!-- row -->
    </div> <!-- container -->
</section>
<!--====== PAGE BANNER PART ENDS ======-->

<div class="login-register-area pt-60 pb-60">
    <div class="container">
        <div class="row">
            <div class="col-lg-7 col-md-12 ml-auto mr-auto">
                <div class="login-register-wrapper">
                    <div class="tab-content">
                        <div class="login-form-container">
                            <div class="login-register-form">
                                <form action="{% url 'users:user_login' %}" method="POST">
                                    {% csrf_token %}
                                    <label for="username">Username:</label>
                                    <input type="text" name="username" placeholder="Enter Username.." required>
                                    <br>
                                    <label for="password">Password:</label>
                                    <input type="password" name="password" placeholder="Enter Password.." required>
                                    <br>
                                    <input class="btn btn-success btn-md"type="submit" name="submit" value="Login">
                                
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!--====== PATNAR LOGO PART ENDS ======-->

 <!-- <h3>Please Login:</h3>
 
<form method="POST">
    {% csrf_token %}
    {{ form |crispy }}
     <input type="text" name="user-name" placeholder="Username">
                                    <input type="password" name="user-password" placeholder="Password"> 
    <div class="button-box">
        <div class="login-toggle-btn">
            <input type="checkbox">
            <label>Remember me</label>
            <a href="{% url 'users:user_register' %}">Register?</a>
        </div>
        <button class="default-btn" type="submit"><span>Login</span></button>
    </div>
</form> -->

{% endblock content %}

Elearning-master/users/templates/logout.html
{% extends "base.html" %}
{% block content %}
    <h2>You have been logged out</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a href="{% url 'users:user_login' %}">Log In Again</a>
        </small>
    </div>
{% endblock content %}

Elearning-master/users/templates/profile.html
{% extends "base.html" %}
{% block content %}
<!--====== PAGE BANNER PART START ======-->

<section id="page-banner" class="pt-105 pb-110 bg_cover" data-overlay="8" style="background-image: url('/static/images/page-banner-1.jpg')">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="page-banner-cont">
                    <h2>My Profile</h2>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{% url 'course:course_home' %}">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Profile</li>
                        </ol>
                    </nav>
                </div>  <!-- page banner cont -->
            </div>
        </div> <!-- row -->
    </div> <!-- container -->
</section>

<!--====== PAGE BANNER PART ENDS ======-->
    <div class="container">
    <h2>{{ user.username }}'s Profile</h2>
    <div class="border-top pt-3">
        <ul>
            <li>Username: {{ user.username }}</li>
            <li>Email: {{ user.email }}</li>
            
        </ul>
        <small class="text-muted">
            <a href="{% url 'course:course_home' %}">Return to Home</a>
        </small>
    </div>
    </div>
{% endblock content %}

Elearning-master/users/templates/student_register.html
{% extends "base.html" %}

{% load crispy_forms_tags %}
{% block content %}
<!--====== PAGE BANNER PART START ======-->

<section id="page-banner" class="pt-105 pb-110 bg_cover" data-overlay="8"
    style="background-image: url('/static/images/page-banner-1.jpg')">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="page-banner-cont">
                    <h2>Register</h2>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{% url 'course:course_home' %}">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Student Register</li>
                        </ol>
                    </nav>
                </div> <!-- page banner cont -->
            </div>
        </div> <!-- row -->
    </div> <!-- container -->
</section>

<!--====== PAGE BANNER PART ENDS ======-->
<div class="login-register-area pt-60 pb-60">
    <div class="container">
        <div class="row">
            <div class="col-lg-7 col-md-12 ml-auto mr-auto">
                <div class="login-register-wrapper">
                    <div class="tab-content">
                        <div class="login-form-container">
                            <div class="login-register-form">
                                <form method="post">
                                    {% csrf_token %}
                                    {{user_form | crispy}}
                                    {{student_info_form | crispy}}
                                    <!-- <input type="text" name="user-name" placeholder="Username">
                                    <input type="password" name="user-password" placeholder="Password">
                                    <input name="user-email" placeholder="Email" type="email"> -->
                                    <div class="button-box">
                                        <button class="btn btn-success btn-md" type="submit" style="margin-bottom:10px;margin-top:30px;"><span>Register</span></button>
                                    </div>
                                    <div class="pt-3">
                                        <small class="text-muted">
                                            Already Have An Account? <a class="ml-2" href="{% url 'users:user_login' %}">Sign
                                                In</a>
                                        </small>
                                    </div>
                                </form>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- {% if registered %}

<div class="alert alert-success">Congratulations! Registration Successful !!</div>
{% else %}
<form enctype='multipart/form-data' method="POST">
    {{user_form | crispy}}
    {{student_info_form | crispy}}
    {% csrf_token %}

    <input type="submit" name="submit" value="Register">
</form>

{% endif %} -->

{% endblock content %}

Elearning-master/users/templates/user_register.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="bg_cover pt-150" style="background-color:#e6e6fa;padding-bottom: 100px;">


  <div class="container">
    <div class="row text-center course-video" >



        <div class="col-xl-12 col-lg-12">
        <h1 class="text-center"> Choose Your Dream. . .</h1>
        </div>


    </div>
        <br>
    <div class="row">


        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 text-center"  >

            <div class="slider-cont">
                <ul>

                    <li><a data-animation="fadeInUp" data-delay="1.6s" class="main-btn" href="{% url 'users:student_register' %}">Be Master</a></li>
                    <li><a data-animation="fadeInUp" data-delay="1.6s" class="main-btn" href="{% url 'users:instructor_register' %}">Make Master</a></li>

                </ul>
            </div>
        </div>
        <!-- <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6">
            <div class="slider-cont">
                <ul>
                    <li><a data-animation="fadeInUp" data-delay="1.6s" class="main-btn" href="{% url 'users:instructor_register' %}">Make Master</a></li>

                </ul>
            </div>
        </div> -->

    </div>

</div>

  </div>
  {% endblock content %}